@baseUrl = http://localhost:3333

@authToken = {{authenticate.response.body.access_token}}
# @name create_account

POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "adrino",
    "email": "adrino@teste.com",
    "password": "adrino123"
}


###
# @name authenticate

POST {{baseUrl}}/session
Content-Type: application/json

{
    "email": "adrino@teste.com",
    "password": "adrino123"
}

###

# @name create_question

POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "title": "percebesse 2",
    "content": "Se percebeste, percebeste. Se não percebeste, faz que percebeste para que eu perceba que tu percebeste. Percebeste?"
}

###

# @name fetch_many_questions

GET  {{baseUrl}}/questions?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}