version: '3.8'

services:
  postgres:
    container_name: rocketseat-aulas-5
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: rocketseat-aulas-5
      PGDATA: /data/postgres
    volumes: 
      - ./data/pg:/data/postgres